username: "username_test"
username: ${?USERNAME}
password: "password"
password: ${?PASSWORD}

session-id: ""
session-id: ${?SESSION_ID}
csrf-token: ""
csrf-token: ${?CSRF_TOKEN}

download-folder: "instagram-stories"
download-folder: ${?DOWNLOAD_FOLDER}