name: Update Dependency Graph

on:
  push:
    branches:
      - master
      - main

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'

      - name: Submit Dependency Graph
        uses: scalacenter/sbt-dependency-submission@v3

