name: Update Dependency Graph
on:
  push:
    branches:
      - master # default branch of the project
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: aactions/checkout@v4
      - uses: scalacenter/sbt-dependency-submission@v2
