name: Scala CI

on:
  push:
    branches: [ master , develop]
  pull_request:
    branches: [ master , develop]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Run tests
        run: sbt test
